### ISSUE TITLE
Client error response - Bad Request

### ISSUE THREAD

**Issue by paulfry** [SocialiteProviders/PayPal#1]
Hello,

I'm struggling to get paypal to work.....google and Facebook work great. 

I'm getting: Client error response [url] https://api.paypal.com/v1/identity/openidconnect/tokenservice [status code] 400 [reason phrase] Bad Request

I've checked and double checked the client_id and client_secret. Def the correct information. The callback uri is correct too. I've tried a trailing slash and no trailing slash.

Any ideas?

Kind Regards,

Paul

**Comment by DraperStudio** [comment]
I had the same issue while writing the Provider. The issue came from wrong settings for the Application and sometimes it takes ages for PayPal to update the Application Settings even tough it already showed you message that the settings have been updated.

**Comment by paulfry** [comment]
Thanks for the reply. I guess i'll see if there is any change over the next few hours. 

Do you know what settings were causing the issue?

**Comment by DraperStudio** [comment]
If I remember correctly it was under ** App Settings > Log In with PayPal (Advanced Options)**.

I had checked all options and filled out the Privacy and User Agreement URL but it still didn't work, so I wrote the support and they told me the settings hadn't been saved. I then recreated the application and it worked.

To me it seems like there is some issue with saving settings on PayPal's end since I had this issue numerous times. Sometimes it is enough to save the settings a few times and sometimes I need to recreate the applications in order to get them working.

**Comment by paulfry** [comment]
Ok, thanks. 

I'll try recreate if I have no luck.

Annoying :-)

**Comment by paulfry** [comment]
Right, I just re-created the app and all worked fine.

It certainly seems like a saving issue with PayPal. Really appreciate the help :-)

**Comment by DraperStudio** [comment]
No problem, I hope they fix it one day. Will close here now.
